[package]
name = "ussr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.13.2"
bevy_ecs = "0.13.2"
chrono = "0.4.38"
color-eyre = "0.6.3"
env_logger = "0.11.3"
eyre = "0.6.12"
log = "0.4.21"
tokio = {version = "1.37.0", features = ["full"]}
