[package]
name = "ussr"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = "0.13.2"
chrono = "0.4.38"
env_logger = "0.11.3"
log = "0.4.21"
ussr-net = { version = "0.1.0", path = "../ussr-net" }
