[package]
name = "ussr-protocol"
version = "0.1.0"
edition = "2021"
build = "build/mod.rs"

[dependencies]
bytes = "1.6.0"
paste = "1.0.15"
strum = "0.26"
strum_macros = "0.26"
thiserror = "1.0.61"
ussr-buf = { version = "0.1.0", path = "../ussr-buf" }
ussr-nbt = { version = "0.1.0", path = "../ussr-nbt" }

[build-dependencies]
specmc-protocol = { version = "0.1.9", features = ["1_7_2"] }
specmc-base = "0.1.11"
